import {
  CurrencyDollarIcon,
  LaptopIcon,
  TrendUpIcon,
  BriefcaseIcon,
  TagIcon,
  GiftIcon,
  StarIcon,
  PiggyBankIcon,
  CarIcon,
  GameControllerIcon,
  FirstAidKitIcon,
  GraduationCapIcon,
  TShirtIcon,
  WrenchIcon,
  HouseIcon,
  MonitorIcon,
  AirplaneIcon,
  ArrowsCounterClockwiseIcon,
  ForkKnifeIcon,
  PawPrintIcon,
  DotsThreeIcon,
  QuestionIcon,
  ShieldIcon,
} from "@phosphor-icons/react";

export const INCOME_CATEGORIES = [
  "Salario",
  "Freelance",
  "Inversiones",
  "Negocio",
  "Venta",
  "Regalo",
  "Bono",
  "Ahorro",
  "Otro",
];

export const EXPENSE_CATEGORIES = [
  "Alimentación",
  "Transporte",
  "Entretenimiento",
  "Salud",
  "Educación",
  "Ropa",
  "Servicios",
  "Seguro",
  "Vivienda",
  "Tecnología",
  "Viajes",
  "Suscripciones",
  "Mascotas",
  "Regalos",
  "Otro",
];

export const CATEGORY_COLORS = {
  // Income
  Salario:       "#34D399",
  Freelance:     "#67E8F9",
  Inversiones:   "#818CF8",
  Negocio:       "#A78BFA",
  Venta:         "#4ADE80",
  Regalo:        "#F472B6",
  Bono:          "#FBBF24",
  Ahorro:        "#10B981",
  // Expenses
  Alimentación:  "#FB923C",
  Transporte:    "#60A5FA",
  Entretenimiento: "#C084FC",
  Salud:         "#34D399",
  Educación:     "#67E8F9",
  Ropa:          "#F472B6",
  Servicios:     "#94A3B8",
  Seguro:        "#38BDF8",
  Vivienda:      "#FBBF24",
  Tecnología:    "#818CF8",
  Viajes:        "#2DD4BF",
  Suscripciones: "#A78BFA",
  Mascotas:      "#F59E0B",
  Regalos:       "#E879F9",
  Otro:          "#64748B",
};

export const CATEGORY_ICONS = {
  // Income
  Salario:       CurrencyDollarIcon,
  Freelance:     LaptopIcon,
  Inversiones:   TrendUpIcon,
  Negocio:       BriefcaseIcon,
  Venta:         TagIcon,
  Regalo:        GiftIcon,
  Bono:          StarIcon,
  Ahorro:        PiggyBankIcon,
  // Expenses
  Alimentación:  ForkKnifeIcon,
  Transporte:    CarIcon,
  Entretenimiento: GameControllerIcon,
  Salud:         FirstAidKitIcon,
  Educación:     GraduationCapIcon,
  Ropa:          TShirtIcon,
  Servicios:     WrenchIcon,
  Seguro:        ShieldIcon,
  Vivienda:      HouseIcon,
  Tecnología:    MonitorIcon,
  Viajes:        AirplaneIcon,
  Suscripciones: ArrowsCounterClockwiseIcon,
  Mascotas:      PawPrintIcon,
  Regalos:       GiftIcon,
  Otro:          DotsThreeIcon,
};

export const DEFAULT_ICON = QuestionIcon;
